# Generated by Django 4.2.4 on 2023-08-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('display_name_alternatives', models.JSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('last_known_institution', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsCountsByYear',
            fields=[
                ('author_id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsIds',
            fields=[
                ('author_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(blank=True, null=True)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('scopus', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_thumbnail_url', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptsAncestors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.TextField(blank=True, null=True)),
                ('ancestor_id', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptsCountsByYear',
            fields=[
                ('concept_id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptsIds',
            fields=[
                ('concept_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(blank=True, null=True)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('umls_aui', models.JSONField(blank=True, null=True)),
                ('umls_cui', models.JSONField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptsRelatedConcepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.TextField(blank=True, null=True)),
                ('related_concept_id', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ror', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('homepage_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_thumbnail_url', models.TextField(blank=True, null=True)),
                ('display_name_acronyms', models.JSONField(blank=True, null=True)),
                ('display_name_alternatives', models.JSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionsAssociatedInstitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.TextField(null=True)),
                ('associated_institution_id', models.TextField(null=True)),
                ('relationship', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionsCountsByYear',
            fields=[
                ('institution_id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionsGeo',
            fields=[
                ('institution_id', models.TextField(primary_key=True, serialize=False)),
                ('city', models.TextField(null=True)),
                ('geonames_city_id', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('country_code', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionsIds',
            fields=[
                ('institution_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(null=True)),
                ('ror', models.TextField(null=True)),
                ('grid', models.TextField(null=True)),
                ('wikipedia', models.TextField(null=True)),
                ('wikidata', models.TextField(null=True)),
                ('mag', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField(null=True)),
                ('alternate_titles', models.JSONField(null=True)),
                ('country_codes', models.JSONField(null=True)),
                ('hierarchy_level', models.IntegerField(null=True)),
                ('parent_publisher', models.TextField(null=True)),
                ('works_count', models.IntegerField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
                ('sources_api_url', models.TextField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishersCountsByYear',
            fields=[
                ('publisher_id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishersIds',
            fields=[
                ('publisher_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(null=True)),
                ('ror', models.TextField(null=True)),
                ('wikidata', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('issn_l', models.TextField(null=True)),
                ('issn', models.JSONField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('works_count', models.IntegerField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
                ('is_oa', models.BooleanField(null=True)),
                ('is_in_doaj', models.BooleanField(null=True)),
                ('homepage_url', models.TextField(null=True)),
                ('works_api_url', models.TextField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourcesCountsByYear',
            fields=[
                ('source_id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourcesIds',
            fields=[
                ('source_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(null=True)),
                ('issn_l', models.TextField(null=True)),
                ('issn', models.JSONField(null=True)),
                ('mag', models.BigIntegerField(null=True)),
                ('wikidata', models.TextField(null=True)),
                ('fatcat', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('doi', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('publication_year', models.IntegerField(null=True)),
                ('publication_date', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('cited_by_count', models.IntegerField(null=True)),
                ('is_retracted', models.BooleanField(null=True)),
                ('is_paratext', models.BooleanField(null=True)),
                ('cited_by_api_url', models.TextField(null=True)),
                ('abstract_inverted_index', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksAuthorships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('author_position', models.TextField(null=True)),
                ('author_id', models.TextField(null=True)),
                ('institution_id', models.TextField(null=True)),
                ('raw_affiliation_string', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksBestOALocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('source_id', models.TextField(null=True)),
                ('landing_page_url', models.TextField(null=True)),
                ('pdf_url', models.TextField(null=True)),
                ('is_oa', models.BooleanField(null=True)),
                ('version', models.TextField(null=True)),
                ('license', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksBiblio',
            fields=[
                ('work_id', models.TextField(primary_key=True, serialize=False)),
                ('volume', models.TextField(null=True)),
                ('issue', models.TextField(null=True)),
                ('first_page', models.TextField(null=True)),
                ('last_page', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksConcepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('concept_id', models.TextField(null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksIds',
            fields=[
                ('work_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(null=True)),
                ('doi', models.TextField(null=True)),
                ('mag', models.BigIntegerField(null=True)),
                ('pmid', models.TextField(null=True)),
                ('pmcid', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('source_id', models.TextField(null=True)),
                ('landing_page_url', models.TextField(null=True)),
                ('pdf_url', models.TextField(null=True)),
                ('is_oa', models.BooleanField(null=True)),
                ('version', models.TextField(null=True)),
                ('license', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('descriptor_ui', models.TextField(null=True)),
                ('descriptor_name', models.TextField(null=True)),
                ('qualifier_ui', models.TextField(null=True)),
                ('qualifier_name', models.TextField(null=True)),
                ('is_major_topic', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksOpenAccess',
            fields=[
                ('work_id', models.TextField(primary_key=True, serialize=False)),
                ('is_oa', models.BooleanField(null=True)),
                ('oa_status', models.TextField(null=True)),
                ('oa_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksPrimaryLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('source_id', models.TextField(null=True)),
                ('landing_page_url', models.TextField(null=True)),
                ('pdf_url', models.TextField(null=True)),
                ('is_oa', models.BooleanField(null=True)),
                ('version', models.TextField(null=True)),
                ('license', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksReferencedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('referenced_work_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksRelatedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.TextField(null=True)),
                ('related_work_id', models.TextField(null=True)),
            ],
        ),
    ]
