# Generated by Django 4.2.4 on 2023-08-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('display_name_alternatives', models.JSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('last_known_institution', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsIds',
            fields=[
                ('author_id', models.TextField(primary_key=True, serialize=False)),
                ('openalex', models.TextField(blank=True, null=True)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('scopus', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_thumbnail_url', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('doi', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('is_retracted', models.BooleanField(blank=True, null=True)),
                ('is_paratext', models.BooleanField(blank=True, null=True)),
                ('cited_by_api_url', models.TextField(blank=True, null=True)),
                ('abstract_inverted_index', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
